### ISSUE TITLE
paring down the dispersion lesson

### ISSUE THREAD

**Issue by mistrm82** [hbctraining/DGE_workshop_salmon_online#15]
The lesson is a bit text heavy and could use some paring down with the use of  bullet points, sub-sectioning etc

@mistrm82 has some ideas that she will implement in a a branched version and do a pull request for review from the team

**Comment by rkhetani** [comment]
https://github.com/hbctraining/DGE_workshop_salmon_online/blob/master/lessons/04b_DGE_DESeq2_analysis.md
