### ISSUE TITLE
GSEgo error

### ISSUE THREAD

**Issue by mistrm82** [hbctraining/DGE_workshop_salmon_online#18]
Error about `no term enriched `.

Should we look into this?

**Comment by rkhetani** [comment]
Note about using a higher numbers of permutations.

**Comment by mistrm82** [comment]
Tried running the code as is in the lesson but I get the no terms enriched. Setting nPerm=2000 or even 5000 is not noticeable in terms of running time, and it results in a set of terms that are now enriched. 

How did terms go from being not significant to significant? The nPerm parameter specifies how many times this randomization is done and more randomizations are performed, the more precise the FDR Q value estimation will be. So at 1000 a good chunk of terms all get the same estimate of 0.07. With more permutations you will find that the individual terms will obtain more accurate values rather than binned shared value.

Problem is, now the term that we use in the lesson for the GSEplot is not showing up. My results have changed.

Solution, remove the GSEgo section and just add a note. Go terms are better assessed with ORA

**Comment by mistrm82** [comment]
updated lesson
