### ISSUE TITLE
for cluster profiler new msigdbr package

### ISSUE THREAD

**Issue by marypiper** [hbctraining/DGE_workshop_salmon_online#22]
updates in cluster profiler use new msigdbr package to query these datasets; however, older method should still work: https://yulab-smu.top/biomedical-knowledge-mining-book/universal-api.html?q=msig#msigdb-analysis

**Comment by rkhetani** [comment]
Add a note to functional analysis lesson

**Comment by mistrm82** [comment]
added it to the main text
