### ISSUE TITLE
Create project with data and folders

### ISSUE THREAD

**Issue by jihe-liu** [hbctraining/DGE_workshop_salmon_online#23]
In the setup lesson (https://hbctraining.github.io/DGE_workshop_salmon_online/lessons/01b_DGE_setup_and_overview.html), provide the project that already contains data and folders, so that there is no need to download data.

**Comment by rkhetani** [comment]
I have created this in Dropbox and it can be downloaded at https://www.dropbox.com/sh/fzep4vx3stceta9/AAA2YAWgromYe6AvT-JBnGzWa?dl=1
