### ISSUE TITLE
apeglm stat removed

### ISSUE THREAD

**Issue by marypiper** [hbctraining/DGE_workshop_salmon_online#25]
Hey all :) 

Maybe you have seen this already, but I just noticed that they have removed the Stat column from the DESeq2 results output after shrinkage using apeglm. The reason for this is well-described by Mike here: https://support.bioconductor.org/p/129277/. Not sure if this is necessary to add to the lesson, but at least just a heads-up.

**Comment by mistrm82** [comment]
added a sentence about it

**Comment by mistrm82** [comment]
thanks @marypiper :)
