### ISSUE TITLE
Adding gene names to KEGG output

### ISSUE THREAD

**Issue by marypiper** [hbctraining/DGE_workshop_salmon_online#26]
Hey all :)

in Clusterprofiler added utility to translate Entrez ID outputs (e.g. from gseKEGG) to gene symbols: https://yulab-smu.top/biomedical-knowledge-mining-book/useful-utilities.html#setReadable

**Comment by rkhetani** [comment]
Double check and add note as necessary (or code, if needed)

**Comment by mistrm82** [comment]
Added this in the materials. Super helpful function, thanks @marypiper !
