### ISSUE TITLE
design formula order

### ISSUE THREAD

**Issue by mistrm82** [hbctraining/DGE_workshop_salmon_online#40]
look at language in lesson and 5b wald test results

order doesn't matter - but as best practice keep main factor last because of certain defaults

**Comment by mistrm82** [comment]
@eberdan @hwick  please check my note created in the design formulas lesson. If it sounds good to you I will make similar mention in the wald test results lesson

**Comment by hwick** [comment]
It looks good to me. You could consider adding. "If your man effect is not in the last position, you will need to specify in [I forget what function] to retrieve coefficients for that effect." But I don't know if that would make that section too long-winded

**Comment by mistrm82** [comment]
thanks @hwick  I'll add something to that effect in the wald test results lesson - I think it will fit better since that is where we talk about coefficients

**Comment by eberdan** [comment]
looks good to me!
