### ISSUE TITLE
Dispersion figure from DESEQ paper

### ISSUE THREAD

**Issue by eberdan** [hbctraining/DGE_workshop_salmon_online#42]
https://hbctraining.github.io/DGE_workshop_salmon_online/lessons/04b_DGE_DESeq2_analysis.html

The close up of the dispersions figure is taken directly from the DESEQ2 paper but the figure is not really explained and none of the acronyms are listed.

**Comment by mistrm82** [comment]
Add a figure caption - helpful for students and instructors

**Comment by mistrm82** [comment]
Made some edits. All of the information describing the figure was a already in the lesson. I shuffled things around to make it more obvious and added a note under the figure to define MLE and MAP. Please take a look @eberdan and @hwick
