### ISSUE TITLE
Broken Link

### ISSUE THREAD

**Issue by benjibromberg** [hbctraining/DGE_workshop_salmon_online#46]
https://hbctraining.github.io/DGE_workshop_salmon_online/lessons/pathway_topology.html

From this page, the link in the below path is not the correct link to the blog post. There is no "www." in the correct link.

"The blog post from [Getting Genetics Done](http://www.gettinggeneticsdone.com/2012/03/pathway-analysis-for-high-throughput.html) provides a step-by-step procedure for using and understanding SPIA."

[Correct Link](
https://gettinggeneticsdone.blogspot.com/2012/03/pathway-analysis-for-high-throughput.html)

**Comment by Gammerdinger** [comment]
Updated link, Thanks for pointing this out!
