### ISSUE TITLE
Formulas in self-learning broken

### ISSUE THREAD

**Issue by Gammerdinger** [hbctraining/DGE_workshop_salmon_online#47]
"I am self-learning bioinformatics using the awesome material prepared by your training program.

For the topic:  
- "Differential Gene Expression Analysis (bulk RNA-seq Part II)";  
- Part III (DESeq2); 
- Section 1. Description of steps for DESeq2, 

The formulas for "How is the dispersion value derived?" are not displayed.
Just thought I would let you know."

**Comment by mistrm82** [comment]
@Gammerdinger  Is this issue resolved? Cannot find the formula any more

**Comment by Gammerdinger** [comment]
@mistrm82 We choose to remove them, but I think there was maybe some conversation but re-introducing them after some tweaks? I think it is fine with them removed as well though.

**Comment by Gammerdinger** [comment]
Meeta and I decided to close this issue
