### ISSUE TITLE
update clustering figure from LRT lesson to reflect y axis change in new version

### ISSUE THREAD

**Issue by hwick** [hbctraining/DGE_workshop_salmon_online#50]
has z score abundance

**Comment by Gammerdinger** [comment]
<img width="562" alt="Screen Shot 2024-05-07 at 12 13 48 PM" src="https://github.com/hbctraining/DGE_workshop_salmon_online/assets/9057053/6f3cc567-6456-4831-a078-70b2fcc3f7ad">

**Comment by Gammerdinger** [comment]
Y-axis is different from the materials

**Comment by mistrm82** [comment]
updated the figure
