### ISSUE TITLE
LRT lesson refers to objects created in previous lessons which students may not have loaded up

### ISSUE THREAD

**Issue by hwick** [hbctraining/DGE_workshop_salmon_online#51]
`dds_lrt `is originally created in Multiple test corrections with:
`dds_lrt <- DESeq(dds, test="LRT", reduced = ~ 1)`
Is referred to later in the LRT lesson

`rld_mat` is originally created in Visualizations self learning:
```
rld <- rlog(dds, blind=T)
rld_mat <- assay(rld)
```
Is referred to later in the in LRT lesson

We should either add a note for how to recreate the objects, or instruct students to save (and load) their environment for each lesson. I think it is easier to just add a note for how to recreate the objects since environments can get confusing and might be conceptually new for students (we don't introduce the concept)

**Comment by mistrm82** [comment]
added notes for each
