### ISSUE TITLE
WGCNA link missing from lesson about network analysis

### ISSUE THREAD

**Issue by hwick** [hbctraining/DGE_workshop_salmon_online#56]
Apparently the link is broken because Horvath left UCLA and is no longer paying for the website

Our best bet is to probably replace with internet archive link to the original, here: https://web.archive.org/web/20230323144343/horvath.genetics.ucla.edu/html/CoexpressionNetwork/Rpackages/WGCNA/

More info about the disappearance and some other links here:
https://www.reddit.com/r/bioinformatics/comments/1cr7m9j/what_happened_to_the_wgcna_tutorial/

**Comment by hwick** [comment]
I've updated the links to the internet archive and noted in the lesson that it's no longer maintained. The only reason I am not closing this issue yet is because we may want to replace WGCNA with another network analysis program that is maintained; however, I'm not sure if there's one that has taken over WGCNA's role in this area. There still seems to be a lot of interest/usage of it.

**Comment by mistrm82** [comment]
Keep mention of WGCNA since ppl are still using it
